### ISSUE TITLE
Strict peer dependencies

### ISSUE THREAD

**Issue by hexus** [hirohe/tweakpane-plugin-search-list#1]
Hi there!

I'm interested in taking this Tweakpane plugin for a spin, but the strict peer dependencies would force me to use `npm update --force` or `npm update --legacy-peer-deps` in order to do so, because you've listed [very specific versions](https://github.com/hirohe/tweakpane-plugin-search-list/blob/c573537f38e0bee4512438f656626b9f0b76c14f/package.json#L65-L66) for Lodash and Tweakpane as the library's peer dependencies.

I was hoping these could be loosened up with a caret:

```json
  "peerDependencies": {
    "lodash": "^4.17.21",
    "tweakpane": "^2.3.0"
  },
```

I expect semver well prevent any breakages here.

Cheers!

**Comment by hirohe** [comment]
thanks for report this problem, it is mistack to set a specific version in peerDependencies

**Comment by hirohe** [comment]
tweakpane 2.2.0 above has huge [refactoring](https://github.com/cocopon/tweakpane/releases), it will break this plugin

i have to do some change too

**Comment by hexus** [comment]
Ah, indeed. Perhaps Tweakpane isn't following semantic versioning so closely if the plugin breaks, then.

Either way, thank you for loosening the dependencies as you have! I'll keep an eye out for an updated version that works with 2.3/3.x.

**Comment by cocopon** [comment]
At this point, semver of Tweakpane is working correctly for users, but not for plugin developers. I may need to separate its core as another package. I plan to fix it after releasing the next major version, sorry for the inconvenience...!

**Comment by hexus** [comment]
No worries at all, thanks for such a swift response and taking it into account! 🙏
